name: Ping Supabase Twice a Week

on:
  schedule:
    - cron: "0 0 * * 3,6" # Runs every Wednesday and Saturday at midnight UTC

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request to Supabase
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" -X GET "https://swiftpaylm.vercel.app/api/ping")
          if [ $response -ne 200 ]; then
            echo "Ping failed with status code $response"
            exit 1
          fi
